### ISSUE TITLE
:word: converts to blank image if not actual emoji tag

### ISSUE THREAD

**Issue by BlueHatbRit** [Bloggify/showdown-emoji#2]
Hi there, I've been using showdown-emoji in mdpdf which now powers [markdown-pdf](https://atom.io/packages/markdown-pdf). We've had an issue for a little while now which seems to be a bug in showdown-emoji from what I can see.

The original issue (https://github.com/travs/markdown-pdf/issues/166, and mirrored on mdpdf https://github.com/BlueHatbRit/mdpdf/issues/30#issuecomment-341296438) shows that emojis which are not recognised will be converted into a blank image, rather than leaving the text as-is.

IE:

_Note: the trailing hash tag was added to allow the back ticks to print in the ticket, not part of original code._

```
```shell
FQDN=`hostname -f  | tr '[:upper:]' '[:lower:]'`
```#
```

Will render ![image](https://user-images.githubusercontent.com/1587409/32304900-b3f62a80-bf48-11e7-81b0-8b69ea9bea47.png)

Would this be considered a bug by showdown-emoji? If not, would you be open to including a flag within the project to leave un-known emojis in their text state rather than converting it to an empty image? I'd be willing to get involved with this as a PR if the change is okay to carry out.

**Comment by IonicaBizau** [comment]
Thanks for the catch!

We could check if the emoji is a valid one, but even in that case we will have to check if it should be converted into an emoji at all: I'm not sure how to check if we are in a code block/inline code element.

Contributions are welcome!

**Comment by BlueHatbRit** [comment]
I feel like most of the problems my users have had will be sorted by first ensuring that invalid emojis are not converted. I think maybe restricting it to outside of code blocks only could be a second step if it's still causing issues.

I can see most of the emoji conversion is being done through emojer, your other module. Where would be the best place to test if the emoji is valid? Would it be in that module, or in this one after the template has been made? Also what would be the preferred way of checking for valid emojis in your opinion? The two approaches I can see would be:

1. Have a list of emojis in one of the modules and check whether the text being converted contains a valid emoji, if so we convert it, otherwise we move onto the next one. This has a drawback of potentially adding maintenance overhead in the future of keeping up to date with current emoji listings from the provider.
2. Do a HTTP request to the resultant image to see if an image is resolved or 404's. This has the obvious drawback of slowing down the module significantly.

**Comment by IonicaBizau** [comment]
I'm on it.

Using [`github-api-emojis`](https://github.com/IonicaBizau/github-api-emojis) we know what emojis are supported. Then, `emojer` should know that it shouldn't replace everything.

https://github.com/IonicaBizau/emojer/pull/8

And finally, here, we tell `emojer` what to replace.

**Comment by BlueHatbRit** [comment]
That's a great fix, thank you @IonicaBizau! Far better than my solutions, I'll roll this into mdpdf asap!

**Comment by IonicaBizau** [comment]
Cool!

Since it's a patch version, it is going to be shipped automatically (`npm install` should do it probably).

**Comment by BlueHatbRit** [comment]
I've just pulled the latest mdpdf and it has pulled the update as you anticipated. I'll close off the issue on mdpdf with credit where credit is due :) Thanks for getting this one fixed @IonicaBizau

**Comment by IonicaBizau** [comment]
Cool! Enjoy! 😁
